title: Hi! I'm Chloe
author: Chloe Chow
email: chloepchow@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I’m an aspiring UX designer, determined to make people’s lives easier by taking out the difficulty. I’m passionate about designing experiences that enable the users’ fullest potential to achieve more.  


# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
